import { api, rows } from "../shared/api.js";
import { escapeHtml, mountAdminSidebar, mountNavigation, notify, requireAdmin } from "../shared/navigation.js";
mountNavigation(); const page = document.body.dataset.adminPage; if (requireAdmin()) { mountAdminSidebar(page); load(); }
async function load() { const target = document.querySelector("#admin-content"); try {
  if (page === "dashboard") { const [general, trips, reports] = await Promise.all([api.admin.statistics(), api.admin.tripStatistics(), api.admin.dashboardStatistics()]); const values = { ...(general?.data || general), ...(trips?.data || trips), ...(reports?.data || reports) }; target.innerHTML = stats(values); return; }
  if (page === "revenue") { const payload = await api.admin.revenue(); target.innerHTML = stats(payload?.data || payload); return; }
  if (page === "users") { const users = rows(await api.admin.users()); target.innerHTML = `<table class="table"><thead><tr><th>Name</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody>${users.map(user => `<tr><td>${escapeHtml(user.name || `${user.first_name || ""} ${user.last_name || ""}`)}</td><td>${escapeHtml(user.email || "")}</td><td>${user.is_active ? "Active" : "Inactive"}</td><td><button class="button subtle" data-user="${escapeHtml(user.id)}" data-active="${user.is_active ? "0" : "1"}">${user.is_active ? "Deactivate" : "Activate"}</button></td></tr>`).join("")}</tbody></table>`; target.querySelectorAll("[data-user]").forEach(button => button.addEventListener("click", async () => { try { await api.admin.userStatus(button.dataset.user, button.dataset.active === "1"); load(); } catch (error) { notify(error.message, true); } })); return; }
  if (page === "create-trip") { document.querySelector("#trip-create-form").addEventListener("submit", async event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); for (const key of ["number_of_travels", "number_of_days", "budget", "estimated_expenses"]) values[key] = Number(values[key]); try { const result = await api.trips.create(values); const trip = result?.data || result; notify("Trip created."); location.assign(`/pages/trip-details.html?id=${encodeURIComponent(trip.id)}`); } catch (error) { notify(error.message, true); } }); return; }
  if (page === "interests") { const render = async () => { const interests = rows(await api.admin.interests()); target.innerHTML = interests.map(item => `<article class="result-card"><h3>${escapeHtml(item.name || item.title)}</h3><button class="button subtle" data-remove="${escapeHtml(item.id)}">Delete</button></article>`).join("") || '<div class="empty">No interests yet.</div>'; target.querySelectorAll("[data-remove]").forEach(button => button.addEventListener("click", async () => { try { await api.admin.removeInterest(button.dataset.remove); render(); } catch (error) { notify(error.message, true); } })); }; await render(); document.querySelector("#interest-form").addEventListener("submit", async event => { event.preventDefault(); try { await api.admin.createInterest(Object.fromEntries(new FormData(event.currentTarget))); event.currentTarget.reset(); render(); } catch (error) { notify(error.message, true); } }); return; }
  if (page === "complaints") { const messages = rows(await api.admin.messages()); target.innerHTML = cards(messages, item => `<p class="eyebrow">${escapeHtml(item.status || "PENDING")}</p><h3>${escapeHtml(item.title || "Complaint")}</h3><p>${escapeHtml(item.description || "")}</p><p>${escapeHtml(item.email || "")} · ${escapeHtml(item.phone || "")}</p><button class="button subtle" data-reply="${escapeHtml(item.id)}">Mark replied</button>`); target.querySelectorAll("[data-reply]").forEach(button => button.addEventListener("click", async () => { try { await api.admin.messageStatus(button.dataset.reply, "replied"); button.closest("article").remove(); } catch (error) { notify(error.message, true); } })); return; }
  if (page === "reviews") { const reviews = rows(await api.admin.reviews()); target.innerHTML = cards(reviews, item => `<h3>${escapeHtml(item.title || "Review")}</h3><p>${escapeHtml(item.comment || item.content || "")}</p><button class="button" data-decision="approve" data-id="${escapeHtml(item.id)}">Approve</button> <button class="button subtle" data-decision="reject" data-id="${escapeHtml(item.id)}">Reject</button>`); target.querySelectorAll("[data-decision]").forEach(button => button.addEventListener("click", async () => { try { await api.admin.reviewDecision(button.dataset.id, button.dataset.decision); button.closest("article").remove(); } catch (error) { notify(error.message, true); } })); return; }
  if (page === "site-settings") { const form = document.querySelector("#site-settings-form"); const settings = rows(await api.admin.settings()); const current = settings[0] || {}; form.elements.settings_id.value = current.id || ""; const fields = [["name", "Site name", "text"], ["phone", "Phone", "tel"], ["slogan", "Slogan", "text"], ["facebook", "Facebook URL", "url"], ["instagram", "Instagram URL", "url"], ["logo", "Logo", "file"]]; target.innerHTML = fields.map(([name, label, type]) => `<div class="field"><label>${label}</label><input name="${name}" type="${type}" ${type === "file" ? 'accept="image/png,image/jpeg,image/svg+xml"' : `value="${escapeHtml(current[name] || "")}"`} ${current.id || type !== "file" ? "" : "required"}></div>`).join(""); form.addEventListener("submit", async event => { event.preventDefault(); const data = new FormData(form); const id = data.get("settings_id"); data.delete("settings_id"); if (!data.get("logo")?.size) data.delete("logo"); try { if (id) await api.admin.updateSettings(id, data); else await api.admin.createSettings(data); notify("Site settings saved."); } catch (error) { notify(error.message, true); } }); }
} catch (error) { target.innerHTML = `<div class="empty">${escapeHtml(error.message)}</div>`; } }
function stats(values) { return Object.entries(values || {}).map(([key, value]) => `<article class="result-card"><p class="eyebrow">${escapeHtml(key.replaceAll("_", " ").toUpperCase())}</p><h2>${escapeHtml(typeof value === "object" ? JSON.stringify(value) : value)}</h2></article>`).join("") || '<div class="empty">No statistics were returned.</div>'; }
function cards(items, content) { return items.length ? items.map(item => `<article class="result-card">${content(item)}</article>`).join("") : '<div class="empty">No records returned.</div>'; }
